      - name: Build APK
        run: |
          gradle :app:assembleDebug --no-daemon

      - name: Check source files
        run: |
          echo "===== MAIN ACTIVITY ====="
          cat app/src/main/java/com/realmofaruna/MainActivity.java
          echo "===== SEARCH TEXT LAMA ====="
          grep -R "APK BERHASIL BERJALAN" . || true
          echo "===== SEARCH WEBVIEW BARU ====="
          grep -R "WEBVIEW BARU" app || true

      - name: Find APK
        run: |
          echo "Mencari APK..."
          find . -type f -name "*.apk" -print
